version: '3'

services:
    rasa:
        build: ./rasa-os-server
        # image: rasa/rasa:latest-full
        container_name: rasa-ros
        volumes:
          - ./rasa-os-server:/usr/src/app
          - ./rasa-os-server/models:/usr/src/app/models
        ports:
          - 5005:5005
