version: '3'

services:
    rasa:
        build: ./rasa-os-server
        # image: rasa/rasa:latest-full
        container_name: rasa-ros
        volumes:
          - ./rasa-os-server:/usr/src/app
        ports:
          - 5005:5005
    rasa-db:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=rasa
          - POSTGRES_PASSWORD=rasa
          - POSTGRES_DB=rasa
        ports:
          - 5432:5432
